### ISSUE TITLE
Background Map & Image not loading

### ISSUE THREAD

**Issue by Tabajara77** [jean-knapp/windows-source-modding-tool#22]
I've set up both background map and image when creating a new chapter. But when launching the mod, it doesn't load - it act as missing texture. However, the files (at /console and /vgui folders) are created in there. Something isn't saving or working right to load those files.

Mod created on HL2 EP Two

![image](https://user-images.githubusercontent.com/4042019/72232165-1b755280-359e-11ea-8c0b-462eb1135f84.png)
![image](https://user-images.githubusercontent.com/4042019/72232245-9179b980-359e-11ea-9177-44b6394306b9.png)

**Comment by jean-knapp** [comment]
Could you check if the search paths are correct?

**Comment by jean-knapp** [comment]
I'll consider this was a search paths problem and close it. Let me know if it happens again.
