### ISSUE TITLE
A lot of unhandled Exception

### ISSUE THREAD

**Issue by Moltard** [jean-knapp/windows-source-modding-tool#43]
Hello, so I saw your tool posted on Source Engine discord and I tried it to see.

It looks great but there are a lot of issues, that maybe you didnt encounter when testing.

For example, the skybox editor. pressing the save button with no picture will throw an error
"System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à source_modding_tool.Materials.SkyboxEditor.saveButton_ItemClick(Object sender, ItemClickEventArgs e)
   à DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)"

 (sorry for the French, Windows translated the exception)

or even selecting one of the skybox from the list will throw an error (System.ArgumentNullException: value cannot be null)

---

Pressing the 'Hammer (propper)' button throws an error

System.ComponentModel.Win32Exception (0x80004005): Le fichier spécifié est introuvable
   à System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   à System.Diagnostics.Process.Start()
   à SourceSDK.Hammer.RunPropperHammer(Mod mod, PackageFile packageFile) dans D:\Files\Development\CS\windows-source-modding-tool\SourceSDK\Hammer.cs:ligne 39
   à source_modding_tool.MainForm.menuModeling_ItemClick(Object sender, ItemClickEventArgs e)

I guess it cant find propper.exe (i have it in my bin folder of csgo though).

---

the vmf to mdl also seems to not work. this time it does find propper.exe but tries to execute a non existant function ?
![image](https://user-images.githubusercontent.com/65123883/114212176-d0451d80-9961-11eb-804a-88ff8504a5fe.png)

GetSpewOutputColor

For reference, I have Propper 2013 installed in the bin folder, but i doubt the functions of it are any different.

---

the fog previewer tries to launch csgo from the csgo.exe, but it throws the same error you would get if you launched it yourself

![image](https://user-images.githubusercontent.com/65123883/114212352-05ea0680-9962-11eb-8cc2-11148be559ae.png)

There might be more crash problem (it doesnt actually crash and still let you continue even if the exception are not handled), but I couldnt really get any tool to work

Thanks for reading

**Comment by jean-knapp** [comment]
Fixed the problems on Skybox Editor (it was remade from scratch).

**Comment by jean-knapp** [comment]
- [ ] Fix System.NullReferenceException in SkyboxEditor.
- [ ] Fix Propper for CSGO (perhaps I should treat CSGO as a different branch of Source?).
- [ ] Fix VMF to MDL for CSGO (perhaps I should treat CSGO as a different branch of Source?).

**Comment by jean-knapp** [comment]
There is trouble running the tool with CSGO. It should be fixed when Hammer++ gets released. I disabled the features for CSGO meanwhile.
