### ISSUE TITLE
Soundscape editor saving with incorrect format.

### ISSUE THREAD

**Issue by Dschartt** [jean-knapp/windows-source-modding-tool#50]
I brought this up in the map labs discord, when saving a file in the soundscape editor, it ruins the formatting of the whole file.

[soundscapes_dschartt (1).txt](https://github.com/jean-knapp/windows-source-modding-tool/files/7422184/soundscapes_dschartt.1.txt)

![madewithmodtooltm](https://user-images.githubusercontent.com/77544434/138979031-667ce654-55c1-4276-9593-0868e39ad657.PNG)

**Comment by jean-knapp** [comment]
Fixed on v1.2.0-beta.
